server:
  port: 8080
spring:
  config:
    encoding: UTF-8
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 123
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.H2Dialect
      show_sql: true
      format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
      web-allow: 0.0.0.0/0
      web-allow-others: true

